export const apiKey = 'be2148fd49414ef9877172951230512';

export const weatherImages = {
    'Переменная облачность': require('../screens/assets/animations/weather/partly_cloudy.json'),
    'Местами облачно': require('../screens/assets/animations/weather/partly_cloudy.json'),
    'Умеренный дождь': require('../screens/assets/animations/weather/maybe_rain.json'),
    'Временами умеренный дождь': require('../screens/assets/animations/weather/maybe_rain.json'),
    'Возможен кратковременный дождь': require('../screens/assets/animations/weather/maybe_rain.json'),
    'Солнечно': require('../screens/assets/animations/weather/sunny.json'),
    'Ясно': require('../screens/assets/animations/weather/sunny.json'),
    'Пасмурно': require('../screens/assets/animations/weather/overcast.json'),
    'Облачно': require('../screens/assets/animations/weather/cloudy.json'),
    'Небольшой дождь': require('../screens/assets/animations/weather/light_rain.json'),
    'Местами дождь': require('../screens/assets/animations/weather/light_rain.json'),
    'Небольшой ливень': require('../screens/assets/animations/weather/light_rain.json'),
    'Небольшой ливневый дождь': require('../screens/assets/animations/weather/light_rain.json'),
    'Умеренный или сильный ливневый дождь': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Местами небольшой дождь': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Кратковременный мелкий дождь': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Дождь': require('../screens/assets/animations/weather/rain.json'),
    'Временами сильный дождь': require('../screens/assets/animations/weather/rain.json'),
    'Сильные ливни': require('../screens/assets/animations/weather/rain.json'),
    'Сильный дождь': require('../screens/assets/animations/weather/rain.json'),
    'Слабый переохлажденный дождь': require('../screens/assets/animations/weather/light_rain.json'),
    'Местами ливни': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Дождь со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Небольшой дождь со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Местами дождь со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Небольшой ливневый дождь со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Умеренные или сильные ливневые дожди со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Умеренный или сильный дождь со снегом': require('../screens/assets/animations/weather/rain.json'),
    'Умеренный или холодный дождь с грозой': require('../screens/assets/animations/weather/rain_with_thunder.json'),
    'Местами замерзающая морось': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Умеренный или сильный переохлажденный дождь': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Туман': require('../screens/assets/animations/weather/fog.json'),
    'Переохлажденный туман': require('../screens/assets/animations/weather/fog.json'),
    'Небольшой снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Умеренный снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Поземок': require('../screens/assets/animations/weather/light-snow.json'),
    'Местами снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Небольшой снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Местами небольшой снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Местами умеренный снег': require('../screens/assets/animations/weather/light-snow.json'),
    'Метель': require('../screens/assets/animations/weather/blizzard.json'),
    'Местами сильный снег': require('../screens/assets/animations/weather/blizzard.json'),
    'Умеренный или сильный снег': require('../screens/assets/animations/weather/blizzard.json'),
    'Ледяной дождь': require('../screens/assets/animations/weather/light-snow.json'),
    'Сильный снег': require('../screens/assets/animations/weather/blizzard.json'),
    'Местами грозы': require('../screens/assets/animations/weather/thunderstorm.json'),
    'Местами слабая морось': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Слабая морось': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Небольшой ледяной дождь': require('../screens/assets/animations/weather/light_rain_moderate.json'),
    'Замерзающая морось': require('../screens/assets/animations/weather/light-snow.json'),
    'ЗУмеренный или сильный ледяной дождь': require('../screens/assets/animations/weather/light-snow.json'),
    'Сильная замерзающая морось': require('../screens/assets/animations/weather/light-snow.json'),

    'Дымка': require('../screens/assets/animations/weather/fog.json'),
    'other': require('../screens/assets/animations/weather/partly_cloudy.json'),
};

