export const newsWebsites = {
    'Газета.Ru': 'gazeta.ru',
    'Lenta.ru': 'lenta.ru',
    'ТАСС': 'tass.ru',
    'Известия': 'iz.ru',
    'Хабр': 'habr.com',
    'IXBT': 'ixbt.com',
    'Мэйл.ру': 'mail.ru',
    'Onliner': 'onliner.by',
    'YouTube': 'youtube.com',
    'КиноПоиск': 'kinopoisk.ru',
    'Пикабу': 'pikabu.ru',
    'Ferra.ru': 'ferra.ru',
    'Игромания': 'igromania.ru',
    'Ведомости': 'vedomosti.ru',
    'Биллборд': 'billboard.com',
    'Коммерсантъ': 'kommersant.ru',
    'Канобу': 'kanobu.ru',
    'Apple': 'apple.com',
    'F1NEWS.RU': 'f1news.ru',
    'RGRU': 'rg.ru',
    'Медуза': 'meduza.io',
    'Интерфакс': 'interfax.ru',
    'LIFE': 'life.ru',
    'ВЗГЛЯД': 'vz.ru',
};