export const apiKey = '0b5495ecb98d4adf920140744232012';

export const weatherImages = {
  'Переменная облачность': require('../../assets/animations/weather/partly_cloudy.json'),
  'Местами облачно': require('../../assets/animations/weather/partly_cloudy.json'),
  'Умеренный дождь': require('../../assets/animations/weather/maybe_rain.json'),
  'Временами умеренный дождь': require('../../assets/animations/weather/maybe_rain.json'),
  'Возможен кратковременный дождь': require('../../assets/animations/weather/maybe_rain.json'),
  'Солнечно': require('../../assets/animations/weather/sunny.json'),
  'Ясно': require('../../assets/animations/weather/sunny.json'),
  'Пасмурно': require('../../assets/animations/weather/overcast.json'),
  'Облачно': require('../../assets/animations/weather/cloudy.json'),
  'Небольшой дождь': require('../../assets/animations/weather/light_rain.json'),
  'Местами дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Небольшой ливень': require('../../assets/animations/weather/light_rain.json'),
  'Небольшой ливневый дождь': require('../../assets/animations/weather/light_rain.json'),
  'Умеренный или сильный ливневый дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Местами небольшой дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Кратковременный мелкий дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Дождь': require('../../assets/animations/weather/rain.json'),
  'Временами сильный дождь': require('../../assets/animations/weather/rain.json'),
  'Сильные ливни': require('../../assets/animations/weather/rain.json'),
  'Сильный дождь': require('../../assets/animations/weather/rain.json'),
  'Слабый переохлажденный дождь': require('../../assets/animations/weather/light_rain.json'),
  'Местами ливни': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Дождь со снегом': require('../../assets/animations/weather/rain.json'),
  'Небольшой дождь со снегом': require('../../assets/animations/weather/rain.json'),
  'Местами дождь со снегом': require('../../assets/animations/weather/rain.json'),
  'Небольшой ливневый дождь со снегом': require('../../assets/animations/weather/rain.json'),
  'Умеренные или сильные ливневые дожди со снегом': require('../../assets/animations/weather/rain.json'),
  'Умеренный или сильный дождь со снегом': require('../../assets/animations/weather/rain.json'),
  'Умеренный или холодный дождь с грозой': require('../../assets/animations/weather/rain_with_thunder.json'),
  'Местами замерзающая морось': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Умеренный или сильный переохлажденный дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Туман': require('../../assets/animations/weather/fog.json'),
  'Переохлажденный туман': require('../../assets/animations/weather/fog.json'),
  'Небольшой снег': require('../../assets/animations/weather/light-snow.json'),
  'Умеренный снег': require('../../assets/animations/weather/light-snow.json'),
  'Поземок': require('../../assets/animations/weather/light-snow.json'),
  'Местами снег': require('../../assets/animations/weather/light-snow.json'),
  'Небольшой снег': require('../../assets/animations/weather/light-snow.json'),
  'Местами небольшой снег': require('../../assets/animations/weather/light-snow.json'),
  'Местами умеренный снег': require('../../assets/animations/weather/light-snow.json'),
  'Метель': require('../../assets/animations/weather/blizzard.json'),
  'Местами сильный снег': require('../../assets/animations/weather/blizzard.json'),
  'Умеренный или сильный снег': require('../../assets/animations/weather/blizzard.json'),
  'Ледяной дождь': require('../../assets/animations/weather/light-snow.json'),
  'Сильный снег': require('../../assets/animations/weather/blizzard.json'),
  'Местами грозы': require('../../assets/animations/weather/thunderstorm.json'),
  'Местами слабая морось': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Слабая морось': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Небольшой ледяной дождь': require('../../assets/animations/weather/light_rain_moderate.json'),
  'Замерзающая морось': require('../../assets/animations/weather/light-snow.json'),
  'ЗУмеренный или сильный ледяной дождь': require('../../assets/animations/weather/light-snow.json'),
  'Сильная замерзающая морось': require('../../assets/animations/weather/light-snow.json'),

  'Дымка': require('../../assets/animations/weather/fog.json'),
  'other': require('../../assets/animations/weather/partly_cloudy.json'),
};
